# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character] 
#success_symbol = '[➜](bold green)' 

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Hostname
[hostname]
ssh_only = false
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false
